name: Run migration
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.8
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 3.2
      - name: Run with Gradle
        run: ./gradlew run
